// Generated by gencpp from file flatland_msgs/DebugTopicList.msg
// DO NOT EDIT!


#ifndef FLATLAND_MSGS_MESSAGE_DEBUGTOPICLIST_H
#define FLATLAND_MSGS_MESSAGE_DEBUGTOPICLIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace flatland_msgs
{
template <class ContainerAllocator>
struct DebugTopicList_
{
  typedef DebugTopicList_<ContainerAllocator> Type;

  DebugTopicList_()
    : topics()  {
    }
  DebugTopicList_(const ContainerAllocator& _alloc)
    : topics(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _topics_type;
  _topics_type topics;





  typedef boost::shared_ptr< ::flatland_msgs::DebugTopicList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flatland_msgs::DebugTopicList_<ContainerAllocator> const> ConstPtr;

}; // struct DebugTopicList_

typedef ::flatland_msgs::DebugTopicList_<std::allocator<void> > DebugTopicList;

typedef boost::shared_ptr< ::flatland_msgs::DebugTopicList > DebugTopicListPtr;
typedef boost::shared_ptr< ::flatland_msgs::DebugTopicList const> DebugTopicListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flatland_msgs::DebugTopicList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flatland_msgs::DebugTopicList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::flatland_msgs::DebugTopicList_<ContainerAllocator1> & lhs, const ::flatland_msgs::DebugTopicList_<ContainerAllocator2> & rhs)
{
  return lhs.topics == rhs.topics;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::flatland_msgs::DebugTopicList_<ContainerAllocator1> & lhs, const ::flatland_msgs::DebugTopicList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace flatland_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::flatland_msgs::DebugTopicList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flatland_msgs::DebugTopicList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flatland_msgs::DebugTopicList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flatland_msgs::DebugTopicList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flatland_msgs::DebugTopicList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flatland_msgs::DebugTopicList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flatland_msgs::DebugTopicList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b0eef9a05d4e829092fc2f2c3c2aad3d";
  }

  static const char* value(const ::flatland_msgs::DebugTopicList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb0eef9a05d4e8290ULL;
  static const uint64_t static_value2 = 0x92fc2f2c3c2aad3dULL;
};

template<class ContainerAllocator>
struct DataType< ::flatland_msgs::DebugTopicList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flatland_msgs/DebugTopicList";
  }

  static const char* value(const ::flatland_msgs::DebugTopicList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flatland_msgs::DebugTopicList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] topics\n"
;
  }

  static const char* value(const ::flatland_msgs::DebugTopicList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flatland_msgs::DebugTopicList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.topics);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DebugTopicList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flatland_msgs::DebugTopicList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flatland_msgs::DebugTopicList_<ContainerAllocator>& v)
  {
    s << indent << "topics[]" << std::endl;
    for (size_t i = 0; i < v.topics.size(); ++i)
    {
      s << indent << "  topics[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.topics[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLATLAND_MSGS_MESSAGE_DEBUGTOPICLIST_H
