// Generated by gencpp from file flatland_msgs/DeleteModel.msg
// DO NOT EDIT!


#ifndef FLATLAND_MSGS_MESSAGE_DELETEMODEL_H
#define FLATLAND_MSGS_MESSAGE_DELETEMODEL_H

#include <ros/service_traits.h>


#include <flatland_msgs/DeleteModelRequest.h>
#include <flatland_msgs/DeleteModelResponse.h>


namespace flatland_msgs
{

struct DeleteModel
{

typedef DeleteModelRequest Request;
typedef DeleteModelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DeleteModel
} // namespace flatland_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::flatland_msgs::DeleteModel > {
  static const char* value()
  {
    return "d82dc6474dd88dad5e1615ab1b2ca74c";
  }

  static const char* value(const ::flatland_msgs::DeleteModel&) { return value(); }
};

template<>
struct DataType< ::flatland_msgs::DeleteModel > {
  static const char* value()
  {
    return "flatland_msgs/DeleteModel";
  }

  static const char* value(const ::flatland_msgs::DeleteModel&) { return value(); }
};


// service_traits::MD5Sum< ::flatland_msgs::DeleteModelRequest> should match
// service_traits::MD5Sum< ::flatland_msgs::DeleteModel >
template<>
struct MD5Sum< ::flatland_msgs::DeleteModelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::flatland_msgs::DeleteModel >::value();
  }
  static const char* value(const ::flatland_msgs::DeleteModelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::flatland_msgs::DeleteModelRequest> should match
// service_traits::DataType< ::flatland_msgs::DeleteModel >
template<>
struct DataType< ::flatland_msgs::DeleteModelRequest>
{
  static const char* value()
  {
    return DataType< ::flatland_msgs::DeleteModel >::value();
  }
  static const char* value(const ::flatland_msgs::DeleteModelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::flatland_msgs::DeleteModelResponse> should match
// service_traits::MD5Sum< ::flatland_msgs::DeleteModel >
template<>
struct MD5Sum< ::flatland_msgs::DeleteModelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::flatland_msgs::DeleteModel >::value();
  }
  static const char* value(const ::flatland_msgs::DeleteModelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::flatland_msgs::DeleteModelResponse> should match
// service_traits::DataType< ::flatland_msgs::DeleteModel >
template<>
struct DataType< ::flatland_msgs::DeleteModelResponse>
{
  static const char* value()
  {
    return DataType< ::flatland_msgs::DeleteModel >::value();
  }
  static const char* value(const ::flatland_msgs::DeleteModelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FLATLAND_MSGS_MESSAGE_DELETEMODEL_H
