// Generated by gencpp from file flatland_msgs/MoveModelRequest.msg
// DO NOT EDIT!


#ifndef FLATLAND_MSGS_MESSAGE_MOVEMODELREQUEST_H
#define FLATLAND_MSGS_MESSAGE_MOVEMODELREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace flatland_msgs
{
template <class ContainerAllocator>
struct MoveModelRequest_
{
  typedef MoveModelRequest_<ContainerAllocator> Type;

  MoveModelRequest_()
    : name()
    , pose()  {
    }
  MoveModelRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::flatland_msgs::MoveModelRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flatland_msgs::MoveModelRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveModelRequest_

typedef ::flatland_msgs::MoveModelRequest_<std::allocator<void> > MoveModelRequest;

typedef boost::shared_ptr< ::flatland_msgs::MoveModelRequest > MoveModelRequestPtr;
typedef boost::shared_ptr< ::flatland_msgs::MoveModelRequest const> MoveModelRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flatland_msgs::MoveModelRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flatland_msgs::MoveModelRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::flatland_msgs::MoveModelRequest_<ContainerAllocator1> & lhs, const ::flatland_msgs::MoveModelRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::flatland_msgs::MoveModelRequest_<ContainerAllocator1> & lhs, const ::flatland_msgs::MoveModelRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace flatland_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::flatland_msgs::MoveModelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flatland_msgs::MoveModelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flatland_msgs::MoveModelRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flatland_msgs::MoveModelRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flatland_msgs::MoveModelRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flatland_msgs::MoveModelRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flatland_msgs::MoveModelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aae4d25923daba9de87a1ff045b66b7d";
  }

  static const char* value(const ::flatland_msgs::MoveModelRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaae4d25923daba9dULL;
  static const uint64_t static_value2 = 0xe87a1ff045b66b7dULL;
};

template<class ContainerAllocator>
struct DataType< ::flatland_msgs::MoveModelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flatland_msgs/MoveModelRequest";
  }

  static const char* value(const ::flatland_msgs::MoveModelRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flatland_msgs::MoveModelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"geometry_msgs/Pose2D pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::flatland_msgs::MoveModelRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flatland_msgs::MoveModelRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveModelRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flatland_msgs::MoveModelRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flatland_msgs::MoveModelRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLATLAND_MSGS_MESSAGE_MOVEMODELREQUEST_H
