(cl:defpackage flatland_msgs-srv
  (:use )
  (:export
   "DELETEMODEL"
   "<DELETEMODEL-REQUEST>"
   "DELETEMODEL-REQUEST"
   "<DELETEMODEL-RESPONSE>"
   "DELETEMODEL-RESPONSE"
   "MOVEMODEL"
   "<MOVEMODEL-REQUEST>"
   "MOVEMODEL-REQUEST"
   "<MOVEMODEL-RESPONSE>"
   "MOVEMODEL-RESPONSE"
   "SPAWNMODEL"
   "<SPAWNMODEL-REQUEST>"
   "SPAWNMODEL-REQUEST"
   "<SPAWNMODEL-RESPONSE>"
   "SPAWNMODEL-RESPONSE"
  ))

